version: "3"

# Use these instead of the local directory for building the projects
# to prevent the containers from fighting with external build tools
volumes:
  core_build:
  api_build:

services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=gdlk
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    command: cargo watch -x "run -- server"
    tty: true # Colorize output
    volumes:
      - ./core:/app/core:rw
      - ./api:/app/api:rw
      - core_build:/app/core/target
      - api_build:/app/api/target
    depends_on:
      - db
    environment:
      - RUST_BACKTRACE=1
      - SERVER_HOST=0.0.0.0:8000
      - DATABASE_URL=postgres://root:root@db/gdlk
    ports:
      - "8000:8000"
