version: "3.2"

services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
      cache_from:
        - gcr.io/gdlkit/gdlk-api:${DOCKER_TAG}
    image: gcr.io/gdlkit/gdlk-api:${DOCKER_TAG}
    volumes:
      - ./:/app:rw
    depends_on:
      - db
    environment:
      RUST_BACKTRACE: 1
      DATABASE_URL: postgres://root:root@db/gdlk

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      cache_from:
        - gcr.io/gdlkit/gdlk-frontend:${DOCKER_TAG}
    image: gcr.io/gdlkit/gdlk-frontend:${DOCKER_TAG}
    volumes:
      - ./:/app:rw

  api-prd:
    build:
      context: .
      dockerfile: ./api/prd.Dockerfile
      cache_from:
        - gcr.io/gdlkit/gdlk-api-prd:${DOCKER_TAG}
    image: gcr.io/gdlkit/gdlk-api-prd:${DOCKER_TAG}

  frontend-prd:
    build:
      context: .
      dockerfile: ./frontend/prd.Dockerfile
      cache_from:
        - gcr.io/gdlkit/gdlk-frontend-prd:${DOCKER_TAG}
    image: gcr.io/gdlkit/gdlk-frontend-prd:${DOCKER_TAG}
