version: "3.2"

services:
  # Unlike the other images, this one has to be built and pushed manually.
  # See README for instructions.
  db:
    build: ./db/dev
    image: ghcr.io/lucaspickering/gdlk-db:${DOCKER_TAG}

  api:
    build:
      context: .
      dockerfile: ./crates/api/Dockerfile
      cache_from:
        - ghcr.io/lucaspickering/gdlk-api:${DOCKER_TAG}
    image: ghcr.io/lucaspickering/gdlk-api:${DOCKER_TAG}
    volumes:
      - ./:/app:rw
    depends_on:
      - db
    environment:
      RUST_BACKTRACE: 1
      DATABASE_URL: postgres://root:root@db/gdlk

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      cache_from:
        - ghcr.io/lucaspickering/gdlk-frontend:${DOCKER_TAG}
    image: ghcr.io/lucaspickering/gdlk-frontend:${DOCKER_TAG}
    volumes:
      - ./:/app:rw

  db-prd:
    build: ./db/prd
    image: ghcr.io/lucaspickering/gdlk-db-prd:${DOCKER_TAG}

  api-prd:
    build:
      context: .
      dockerfile: ./crates/api/prd.Dockerfile
      cache_from:
        - ghcr.io/lucaspickering/gdlk-api-prd:${DOCKER_TAG}
    image: ghcr.io/lucaspickering/gdlk-api-prd:${DOCKER_TAG}

  nginx-prd:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: ghcr.io/lucaspickering/gdlk-nginx-prd:${DOCKER_TAG}
