version: "3.7"

# Use these instead of the local directory for building the projects
# to prevent the containers from fighting with external build tools
volumes:
  api_poetry:
  # frontend_core_build:
  # frontend_wasm_build:
  # frontend_node_modules:

services:
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=gdlk
      - POSTGRES_USER=gdlk
      - POSTGRES_PASSWORD=gdlk

  api:
    build: ./api/
    command: ./scripts/start.sh
    # Makes shutdown faster
    init: true
    environment:
      - GDLK_DB_HOST=db
    volumes:
      - ./api/:/app/api:rw
      - api_poetry:/usr/local/lib/python3.9/site-packages
    depends_on:
      - db
    ports:
      - "8000:8000"

  # commented out during api development
  #
  # frontend:
  #   image: ghcr.io/lucaspickering/gdlk-frontend:${DOCKER_TAG}
  #   command: ./docker/run_frontend.sh
  #   init: true # Needed to kill the relay compiler background process
  #   tty: true # Colorize output
  #   environment:
  #     GDLK_API_HOST: http://api:8000
  #     HTTPS: "true"
  #   volumes:
  #     - ./:/app:rw
  #     - frontend_core_build:/app/target
  #     - frontend_wasm_build:/app/crates/wasm/target
  #     - frontend_node_modules:/app/frontend/node_modules
  #   ports:
  #     - "3000:3000"
