version: "3.3"

volumes:
  certs:
  postgres:

secrets:
  # db container
  gdlk_db_root_password:
    external: true
  gdlk_db_app_password:
    external: true

  # db-backup container
  gdlk_cloud_storage_bucket:
    external: true
  gdlk_cloud_storage_key:
    external: true

  # api container
  gdlk_api_secret_key:
    external: true
  gdlk_api_open_id__providers__google__client_id:
    external: true
  gdlk_api_open_id__providers__google__client_secret:
    external: true

services:
  nginx:
    image: ghcr.io/lucaspickering/gdlk-nginx-prd:${DOCKER_TAG}
    # Need mode:host so the client IP gets logged properly
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    environment:
      GDLK_HOSTNAME: # Gets loaded from the env file
      AMPLIFY_API_KEY_FILE: /run/secrets/gdlk_revproxy_amplify_api_key
    volumes:
      - ${GDLK_LOGS_DIR}/nginx:/var/log/nginx:rw
      - certs:/app/certs:ro
    deploy:
      restart_policy:
        condition: any
        delay: 10s

  db:
    image: ghcr.io/lucaspickering/gdlk-db-prd:${DOCKER_TAG}
    environment:
      POSTGRES_DB: gdlk
      POSTGRES_USER: root
      POSTGRES_ROOT_PASSWORD_FILE: /run/secrets/gdlk_db_root_password
      POSTGRES_APP_USER: gdlk
      POSTGRES_APP_PASSWORD_FILE: /run/secrets/gdlk_db_app_password
    secrets:
      - gdlk_db_root_password
      - gdlk_db_app_password
    volumes:
      - postgres:/var/lib/postgresql/data:rw
    deploy:
      restart_policy:
        condition: any
        delay: 10s

  db-backup:
    image: gcr.io/keskne-283621/keskne-postgres-backup-google:latest
    depends_on:
      - db
    environment:
      BACKUP_CRON_SCHEDULE: 0 * * * * # Hourly backups
      POSTGRES_HOST: db
      POSTGRES_USER: root
      DATABASES: gdlk
      POSTGRES_PASSWORD_FILE: /run/secrets/gdlk_db_root_password
      CLOUD_STORAGE_BUCKET_FILE: /run/secrets/gdlk_cloud_storage_bucket
      CLOUD_STORAGE_KEY_FILE: /run/secrets/gdlk_cloud_storage_key
    secrets:
      - gdlk_db_root_password
      - gdlk_cloud_storage_bucket
      - gdlk_cloud_storage_key
    deploy:
      restart_policy:
        condition: any
        delay: 10m

  api:
    image: ghcr.io/lucaspickering/gdlk-api-prd:${DOCKER_TAG}
    depends_on:
      - db
    environment:
      GDLK_DB_HOST: db
      GDLK_DB_NAME: gdlk
      # This user is just for migrations
      GDLK_ROOT_DB_USER: root
      GDLK_ROOT_DB_PASSWORD_FILE: /run/secrets/gdlk_db_root_password
      # This user is for the API to use
      GDLK_APP_DB_USER: gdlk
      GDLK_APP_DB_PASSWORD_FILE: /run/secrets/gdlk_db_app_password
      GDLK_SERVER_HOST: 0.0.0.0:8000
      GDLK_SECRET_KEY_FILE: /run/secrets/gdlk_api_secret_key
      GDLK_GOOGLE_CLIENT_ID_FILE: /run/secrets/gdlk_api_open_id__providers__google__client_id
      GDLK_GOOGLE_CLIENT_SECRET_FILE: /run/secrets/gdlk_api_open_id__providers__google__client_secret
      GDLK_OPEN_ID__HOST_URL: https://${GDLK_HOSTNAME}
      RUST_LOG: info
      RUST_BACKTRACE: full
    secrets:
      - gdlk_db_root_password
      - gdlk_db_app_password
      - gdlk_api_secret_key
      - gdlk_api_open_id__providers__google__client_id
      - gdlk_api_open_id__providers__google__client_secret
    deploy:
      restart_policy:
        condition: any
        delay: 10s
