env_files = [
    { path = "./prd.env", profile = "production" },
    { path = "./dev.env", profile = "development" },
]

# Shortcut for building/pushing prd images
[tasks.dc]
command = "docker-compose"
args = ["-f", "../docker-compose.ci.yml", "${@}"]


# Production deployment tasks
[tasks.certs]
# Only run if the volume doesn't already exist
condition_script = [
'''
if docker volume ls -q | grep -q '^gdlk_certs$'; then
    exit 1
else
    exit 0
fi
'''
]
script = [
'''
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout privkey.pem -out fullchain.pem -subj /CN=${GDLK_HOSTNAME}/
docker run -d --rm --name certs -v gdlk_certs:/app/certs:rw alpine tail -f /dev/null
docker exec certs mkdir -p /app/certs/${GDLK_HOSTNAME}/
docker cp privkey.pem certs:/app/certs/${GDLK_HOSTNAME}/
docker cp fullchain.pem certs:/app/certs/${GDLK_HOSTNAME}/
docker stop -t 0 certs
rm privkey.pem fullchain.pem
'''
]

[tasks.secrets]
script = { file = "./load_secrets.sh" }

[tasks.log-dir]
# Skip this in production cause you normally deploy from a different machine
condition = { profiles = ["development"] }
command = "mkdir"
args = ["-p", "${GDLK_LOGS_DIR}/nginx"]

[tasks.deploy]
dependencies = [
    "certs",
    "secrets",
    "log-dir",
]
command = "docker"
args = ["stack", "deploy", "-c", "./docker-stack.yml", "gdlk"]
