[package]
name = "gdlk_wasm"
version = "0.1.0"
authors = [
    "John Reilly Murray <johnreillymurray@gmail.com>",
    "Lucas Pickering <lucas@lucaspickering.me>",
]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
gdlk = { path = "../core", features = ["wasm"] }
wasm-bindgen = {version =  "0.2.58", features = ["serde-serialize"]}
serde = "^1.0.59"
serde_derive = "^1.0.59"
