*

!.cargo/
!./Cargo.toml
!./Cargo.lock
!./rust-toolchain

!crates/core/src/
!crates/core/Cargo.toml

!crates/api/schema.graphql
!crates/api/Cargo.toml

!crates/wasm/src/
!crates/wasm/Cargo.toml
!crates/wasm/Makefile.toml

!frontend/public/
!frontend/src/
!frontend/config-overrides.js
!frontend/package.json
!frontend/package-lock.json
!frontend/relay.config.js
!frontend/tsconfig.json

!nginx/
