# Generated by Django 3.2.1 on 2021-05-07 18:21

import core.fields
import django.contrib.postgres.functions
from django.contrib.postgres.operations import CryptoExtension
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        CryptoExtension(),  # Enables UUID generation in the DB
        migrations.CreateModel(
            name="HardwareSpec",
            fields=[
                (
                    "id",
                    core.fields.UUIDField(
                        default=django.contrib.postgres.functions.RandomUUID,
                        editable=False,
                        primary_key=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ProgramSpec",
            fields=[
                (
                    "id",
                    core.fields.UUIDField(
                        default=django.contrib.postgres.functions.RandomUUID,
                        editable=False,
                        primary_key=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "hardware_spec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_specs",
                        to="core.hardwarespec",
                    ),
                ),
            ],
        ),
    ]
