# Generated by Django 3.2.1 on 2021-05-11 12:25

import core.fields
from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareSpec',
            fields=[
                ('id', core.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('num_registers', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('num_stacks', models.PositiveSmallIntegerField()),
                ('max_stack_length', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', core.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', core.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('input', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None, validators=[django.core.validators.MaxLengthValidator(256)])),
                ('expected_output', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None, validators=[django.core.validators.MaxLengthValidator(256)])),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleSolution',
            fields=[
                ('id', core.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('name', models.CharField(max_length=50)),
                ('source_code', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_solutions', to='core.player')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_solutions', to='core.puzzle')),
            ],
            options={
                'unique_together': {('puzzle', 'player', 'name')},
            },
        ),
        migrations.AddField(
            model_name='player',
            name='puzzles',
            field=models.ManyToManyField(related_name='players', through='core.PuzzleSolution', to='core.Puzzle'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
