# Generated by Django 3.2.1 on 2021-05-07 20:34

from django.db import migrations
from django.contrib.postgres.operations import CryptoExtension


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        CryptoExtension(),  # Enables UUID generation in the DB
    ]
