# Generated by Django 3.2.1 on 2021-05-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerSolution',
            new_name='PuzzleSolution',
        ),
    ]
