name: Run tests and other checks

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Run Rust tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
      - name: Install dependencies
        run: |
          sudo apt-get install -y libpq-dev
      - name: rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
      - name: test gdlk
        uses: actions-rs/cargo@v1
        with:
          command: test -p gdlk
