name: Run tests and other checks

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-core:
    name: Run clippy and rustfmt on all crates, and run tests on core crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
      - name: Install dependencies
        run: |
          sudo apt-get install -y libpq-dev
      - name: rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
      - name: test gdlk
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p gdlk
  test-api:
    name: Run tests on api crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build API image
        run: docker-compose -f docker-compose.ci.yml build api
      - name: Test API
        run: docker-compose -f docker-compose.ci.yml run api ./docker/run_tests.sh
