name: Lint, Test, and Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint-rust:
    name: "[ALL] Clippy and Rustfmt"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Cache cargo files
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
      - name: Install dependencies
        run: |
          rustup component add rustfmt clippy
      - name: Run rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -D clippy::all

  test-core:
    name: "[CORE] Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Cache cargo files
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
      - name: Run test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p gdlk

  test-wasm:
    name: "[WASM] Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Cache cargo files
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
      - name: Install wasm-pack
        run: curl -sSLf https://rustwasm.github.io/wasm-pack/installer/init.sh | sh
      - name: Run tests
        working-directory: crates/wasm
        # I couldn't get browser tests to work, but node is fine since we aren't
        # doing any DOM stuff
        run: wasm-pack test --node

  build-frontend:
    name: "[FE] Test & Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      # Caching
      - name: Cache cargo files
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            crates/wasm/pkg
          key: ${{ runner.os }}-cargo-wasm-${{ hashFiles('Cargo.lock') }}

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install npm dependencies
        working-directory: frontend
        run: npm install

      # We have to build *first* so we can get typedefs from the wasm crate
      - name: Build
        working-directory: frontend
        run: npm run build

      - name: Typecheck
        working-directory: frontend
        run: npm run tsc

      - name: Lint
        working-directory: frontend
        run: npm run lint

      - name: Archive build
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: frontend/dist

  # Deploy only on master
  deploy-frontend:
    name: "Deploy frontend"
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    needs:
      - lint-rust
      - test-core
      - test-wasm
      - build-frontend
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Download build artifact
        id: download
        uses: actions/download-artifact@v2
        with:
          name: frontend-build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: ${{ steps.download.outputs.download-path }}
          clean: true
