name: Linting and Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Clippy and Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
      - name: Install dependencies
        run: |
          sudo apt-get install -y libpq-dev
      - name: Run rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
  test-core:
    name: Test core crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: core/target
          key: ${{ runner.os }}-cargo-build-target-core-${{ hashFiles('**/Cargo.lock') }}
      - name: Run test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p gdlk
  test-api:
    name: Test API crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build API image
        run: docker-compose -f docker-compose.ci.yml build api
      - name: Test API
        run: docker-compose -f docker-compose.ci.yml run api ./docker/run_tests.sh
